include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # ---- CONST OPTIMIZATION ----
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_literals_to_create_immutables: true

    # ---- CLEAN CODE ----
    avoid_print: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_this: true
    unnecessary_null_checks: true
    unnecessary_nullable_for_final_variable_declarations: true

    # ---- PERFORMANCE ----
    avoid_redundant_argument_values: true
    avoid_unnecessary_containers: true

    # ---- SAFETY ----
    always_declare_return_types: true
    cancel_subscriptions: true
    close_sinks: true

    # ---- STYLE ----
    use_key_in_widget_constructors: true
    sized_box_for_whitespace: true
    sort_child_properties_last: true
    prefer_final_locals: true
